### ISSUE TITLE
Running the target "mp-hp-view.owl" in Makefile fails (Inconsistent Ontology)

### ISSUE THREAD

**Issue by matentzn** [obophenotype/upheno#254]
Running the target in the makefile fails with this exception:
`Exception in thread "main" owltools.cli.AssertInferenceTool$InconsistentOntologyException: Logic inconsistencies found, count: 10
	at owltools.cli.AssertInferenceTool.assertInferences(AssertInferenceTool.java:622)
	at owltools.cli.CommandRunner.assertInferredSubClassAxioms(CommandRunner.java:4996)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4610)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
make: *** [mp-hp-r.owl] Error 1
`

Note that the following classes seem to be unsatisfiable (I also checked them manually in Protege. Explanation attached in image. From eyeballing this it boils right down to the assertion that blood is modelled as a continuant, and the interleukin receptor binding is an occurrent, which is part of blood):

`2018-01-17 14:12:12,203 ERROR (AssertInferenceTool:620) PROBLEM: Unsatisfiable: MP:0008616 'abnormal circulating interleukin-12 level'
2018-01-17 14:12:12,203 ERROR (AssertInferenceTool:620) PROBLEM: Unsatisfiable: MP:0008649 'abnormal circulating interleukin-23a level'
2018-01-17 14:12:12,204 ERROR (AssertInferenceTool:620) PROBLEM: Unsatisfiable: MP:0008617 'increased circulating interleukin-12 level'
2018-01-17 14:12:12,204 ERROR (AssertInferenceTool:620) PROBLEM: Unsatisfiable: MP:0008618 'decreased circulating interleukin-12 level'
2018-01-17 14:12:12,204 ERROR (AssertInferenceTool:620) PROBLEM: Unsatisfiable: MP:0008619 'abnormal circulating interleukin-23 level'
2018-01-17 14:12:12,204 ERROR (AssertInferenceTool:620) PROBLEM: Unsatisfiable: MP:0008620 'increased circulating interleukin-23 level'
2018-01-17 14:12:12,204 ERROR (AssertInferenceTool:620) PROBLEM: Unsatisfiable: MP:0008621 'decreased circulating interleukin-23 level'
2018-01-17 14:12:12,204 ERROR (AssertInferenceTool:620) PROBLEM: Unsatisfiable: MP:0008643 'abnormal circulating interleukin-12a level'
2018-01-17 14:12:12,204 ERROR (AssertInferenceTool:620) PROBLEM: Unsatisfiable: MP:0008644 'increased circulating interleukin-12a level'
2018-01-17 14:12:12,204 ERROR (AssertInferenceTool:620) PROBLEM: Unsatisfiable: MP:0008645 'decreased circulating interleukin-12a level'`

<img width="791" alt="screen shot 2018-01-17 at 14 28 29" src="https://user-images.githubusercontent.com/7070631/35047747-c0dfff9c-fb92-11e7-8cf0-df4fc47785fb.png">

**Comment by matentzn** [comment]
I double checked the current release of the mammalian phenotype ontology, and indeed it is broken. I made a ticket, I hope they can fix it fast.

**Comment by matentzn** [comment]
The question remains whether we want the pipeline overall to fail if there are unsatisfiable classes in the ontology..

**Comment by drseb** [comment]
"part_of" should probably be "occurs_in" !?

**Comment by matentzn** [comment]
@drseb Thats exactly what I recommended to them as well! 👍

**Comment by balhoff** [comment]
@drseb @matentzn see https://github.com/obophenotype/mammalian-phenotype-ontology/issues/2535

**Comment by cmungall** [comment]
On 17 Jan 2018, at 7:26, matentzn wrote:

> The question remains whether we want the pipeline overall to fail if 
> there are unsatisfiable classes in the ontology..

Yes. But first we need to make sure we iron out all remaining issues, 
ensure the coherency check runs in travis in a timely fashion, and that 
curators are comfortable using Protege to track them down.

**Comment by balhoff** [comment]
I am going to close this since this target works now. I am otherwise working on making the travis checks pass (they do now actually run—they have been failing for a silly reason for a long time).
