### ISSUE TITLE
Regenerating *-bestmatches.tsv fails because of missing properties files

### ISSUE THREAD

**Issue by matentzn** [obophenotype/upheno#276]
I am trying to regenerate the [bestmatches](https://github.com/obophenotype/upheno/tree/master/mappings) tsv files, (https://github.com/obophenotype/upheno/tree/master/mappings). The *all_mappings* target in the make files is dependent on various *.properties* files that are supposed to be located in the mappings directory itself.. But they are not there, so the process fails. Any suggestions highly welcome @cmungall @balhoff 

```
owltools  vertebrate-compute.obo --make-default-abox --fsim-compare-atts -p mappings/zp-to-hp-sim.properties -o mappings/zp-to-hp-match.tbl.tmp && mv mappings/zp-to-hp-match.tbl.tmp mappings/zp-to-hp-match.tbl
Exception in thread "main" java.io.FileNotFoundException: mappings/zp-to-hp-sim.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at owltools.cli.Sim2CommandRunner.loadProperties(Sim2CommandRunner.java:932)
	at owltools.cli.Sim2CommandRunner.loadProperties(Sim2CommandRunner.java:904)
	at owltools.cli.Sim2CommandRunner.fsimCompareAtts(Sim2CommandRunner.java:1147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4610)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
make: *** [mappings/zp-to-hp-match.tbl] Error 1
```

**Comment by balhoff** [comment]
I can't help, but maybe we should also check with @drseb.

**Comment by drseb** [comment]
Owltools is for @cmungall . I did not create these files

**Comment by cmungall** [comment]
See the above PR for conf files.

I'd do this using owlsim3 or ontobio for this now

**Comment by matentzn** [comment]
Great, thanks Chris.
