### ISSUE TITLE
FMA import fails

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#66]
Originally reported on Google Code with ID 65
```
Hi,

the command

make imports/fma_import.owl

currently fails on my computer. Is there any known issue?

If fails with:
...
015-01-27 11:30:04,884 INFO  (ParserWrapper:78) Finished loading ontology: null from:
file:...phenotype-ontologies-googlecode/ontology/mirror/composite-fma.owl
2015-01-27 11:30:04,885 ERROR (CommandRunner:3992) could not parse:mirror/composite-fma.owl
org.semanticweb.owlapi.io.OWLOntologyCreationIOException: ...phenotype-ontologies-googlecode/ontology/mirror/composite-fma.owl
(No such file or directory)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:214)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:829)
...
```

Reported by `dr.sebastian.koehler` on 2015-01-27 10:31:37

**Comment by drseb** [comment]
we don't import fma anymore
